services:
  - type: web
    name: agriscan-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10.13
    region: oregon

