services:
  - type: web
    name: agriscan-backend
    env: python
    buildCommand: |
      pyenv install 3.10.13 --skip-existing
      pyenv global 3.10.13
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10.13
    region: oregon
