services:
  - type: web
    name: agriscan-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon
    pythonVersion: 3.10
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE
        sync: false
