services:
  - type: web
    name: agriscan-fullstack
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build && cd ..
      cp -r frontend/dist/* backend/static/
    startCommand: python backend/app.py
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
